Generating new schema
andresromeroh/json_yml_utility pull request #1
Opened 2022-04-25 13:24 UTC by andrsGutirrz

2022-04-25 17:46 UTC, badilladrian commented on README.md
> +1) Make the script work: *
@andrsGutirrz  make the utility readme kindly

2022-04-25 17:47 UTC, badilladrian commented on app/create_schema_test.py
> +                    "name": model['metadata']['name'],  # TODO: confirm this is correct?
Correct

2022-04-25 17:51 UTC, badilladrian commented on app/create_schema_test.py
> +                    "description": '',  # model['description'],  # TODO: which is the field
`        "source.hrdm_ingest.icims_raw.company": {
            "metadata": {
                "type": "BASE TABLE",
                "schema": "ICIMS",
                "name": "COMPANY", <<---- NAME
                "database": "HR_RAW_QA",
                "comment": "RAW TABLE FOR ICIMS COMPANY",  <<-- DESCRIPTION
                "owner": "_DB_HR_RAW_QA_ICIMS_OWN"
            },`

2022-04-25 17:59 UTC, badilladrian commented on app/create_schema_test.py
> +                    'original_file_path': '',  # model['original_file_path'],  # TODO: which is the field
The manifest provides where exactly the model is at the (whole) project structure (we have just a mini-fraction).

But, the same issue is presented on both scenarios-- Catalog does not contains the path of the .SQL model,
This is needed to know where to write the yml file

the method def write_yaml <- uses this path to match the yml with each model.

On the full extend project, as you can see the path structure can be more complex- so not all models are in the same directory, so the write_yaml NEEDS to know where to write the new generated yml accordingly to its model.

For this; I would suggest creating a new method that would go to app/ <- and make a dict with all the folder/files structures that i finds.

I.E.


app/
--- models (3)
--- other_models (5)
--- more_models (2)

Create a new method def generate_model_directory: --> output a dict with above structure

I suggest the following 
`for path, dirs, files in os.walk("."):
    print path
    for file in files:
        print os.path.join(path, file)
`

so there is no dependencies with the source-files to know where the models live in the project

2022-04-25 18:02 UTC, badilladrian commented on app/create_schema_test.py
> +                    'description': column.get(''),  # TODO: which is the field
`            "columns": {
                "RAW_DATA": { 
                    "type": "VARIANT",   <---- this the DataType we need to add this! 
                    "index": 1,
                    "name": "RAW_DATA",  <---- this the colum name 
                    "comment": null  <---- this the description for column
                },
                "RAW_INSERTED_TIMESTAMP": {
                    "type": "TIMESTAMP_TZ",
                    "index": 2,
                    "name": "RAW_INSERTED_TIMESTAMP",
                    "comment": null
                },
                "RAW_FILENAME": {
                    "type": "TEXT",
                    "index": 3,
                    "name": "RAW_FILENAME",
                    "comment": null
                }
            },`
            
            Gotta iterate over each column

2022-04-25 18:24 UTC, badilladrian requested changes
Added some comments

2022-04-25 18:25 UTC, badilladrian commented on app/create_schema_test.py
> +                        'type': column['type'],
correct

2022-04-25 18:34 UTC, badilladrian commented on app/schema_test.yml
> +version: 2
@andrsGutirrz Here is the expected output for company

version: 2
models:
  - name: company
    description: 'RAW TABLE FOR ICIMS COMPANY'
    dbt_utils.recency:
      datepart: 
      field: 
      interval: 1
      tags: timeliness
      severity: warn
    dbt_expectations.expect_column_distinct_count_to_equal_other_table:
      column_name: 
      row_condition: 
      compare_model: 
      compare_column_name: 
      compare_row_condition: true
      tags: completeness
      severity: warn
    meta:
      slo:
        included: true
        delivery_time_ct:
        offset:
        is_static:
        contact:
        tag:
      ownership:
        team_id:
        ddo_delegate:
        ddo_delegate_ldap:
        subject_matter_expert:
        subject_matter_expert_ldap:
        approver:
        approver_ldap:
        approver_role:
      detailed_description:
        dataset_granularity:
        classification:
        classification_rationale:
        sensitive:
        is_degraded:
        comments:
      build_requirements:
        link_to_builder_code:
        link_to_orchestration_tool:
        link_to_design_document:
      origination:
        refresh_cadence:
        refresh_schedule:
      filters_and_limitations:
        standard_filters_at_consumption:
        general_limitations:
        field_discontinuities_irregularities:
        missing_data:
      data_access:
        access_controls:
        access_controls_review:
      data_quality:
        health_check:
  - name: raw_data
    description: 
    tests:
    - not_null:
        tags: validity
        severity: warn
    meta:
      type: variant
      privacy_classification: 
      ldm_model: 
      ldm_attribute: null
      datasource: 
      field: 
      comments: ''
  - name: raw_inserted_timestamp
    description: 
    tests:
    - not_null:
        tags: validity
        severity: warn
    meta:
      type: timestamp_tz
      privacy_classification: 
      ldm_model: 
      ldm_attribute: null
      datasource: 
      field: 
      comments: ''
  - name: raw_filename
    description: 
    tests:
    - not_null:
        tags: validity
        severity: warn
    meta:
      type: text
      privacy_classification: 
      ldm_model: 
      ldm_attribute: null
      datasource: 
      field: 
      comments: ''
      
      
     this is the goal output

2022-04-25 18:35 UTC, andrsGutirrz commented on app/schema_test.yml
> +version: 2
That's awesome, thanks

2022-04-25 20:13 UTC, badilladrian commented on app/create_schema_test.py
> +            # self.process_models()
@andrsGutirrz  last not least--- uncomment this back!

def process_models as it has
                    f"Error processing {model_obj['models'][0]['name']} with error '{error}'")
                    
just to check if the access of the obj model is still the same, or this model_obj['models'][0]['name'] should be modified as well on this method for the new source catalog.json

2022-04-26 04:46 UTC, andrsGutirrz commented on README.md
> +1) Make the script work: *
Done

2022-04-26 04:46 UTC, andrsGutirrz commented on app/create_schema_test.py
> +                    "name": model['metadata']['name'],  # TODO: confirm this is correct?
Done

2022-04-26 04:46 UTC, andrsGutirrz commented on app/create_schema_test.py
> +                    "description": '',  # model['description'],  # TODO: which is the field
Done

2022-04-26 04:47 UTC, andrsGutirrz commented on app/create_schema_test.py
> +                    'original_file_path': '',  # model['original_file_path'],  # TODO: which is the field
Using another approach. 
To create the route where we save the output yml, that path is the current path + model name

2022-04-26 04:47 UTC, andrsGutirrz commented on app/create_schema_test.py
> +                    'original_file_path': '',  # model['original_file_path'],  # TODO: which is the field
![image](https://user-images.githubusercontent.com/16330583/165223711-8d0c0a08-bdff-40a5-b158-4978de70b17e.png)

2022-04-26 04:47 UTC, andrsGutirrz commented on app/create_schema_test.py
> +                        'type': column['type'],
Done

2022-04-26 04:48 UTC, andrsGutirrz commented on app/create_schema_test.py
> +            # self.process_models()
No change required, this is running well

2022-04-28 19:42 UTC, closed without merging